### PR TITLE
delete .pyc files, more renamings and imports to make testing easier

### PR DESCRIPTION
**Pull request by dimpase**
1st things first, basic cleanup. .pyc files are autogenerated from .py files, no need to store them in the repo.

### CODE REVIEW

**Comment by dimpase** [comment]
I didn't check that renaming .sage -> .py caused issues. Syntax of .sage files is slighly different from standard python...

**Comment by dimpase** [comment]
OK, it works now with these renamings

**Comment by dimpase** [comment]
IMHO it can be merged now - we'll do more later.

**Comment by SeaGriff** [comment]
Oh this is wonderful, thank you!

**Pull request merged**
